use crate::{Bundle, Dependency, Manifest};
use std::io;
use toml::{Table, Value};

pub const GENERATED_HEADER: &str = "# Generated by Ruby Butler. Do not edit.\n# Edit the source Gemfile and project settings instead.\n# Regenerate with rb export-gemfile when source files change.\n";

pub(crate) fn render_normalized(value: &impl serde::Serialize) -> Result<Value, toml::ser::Error> {
    let mut value = Value::try_from(value)?;
    if let Some(bundle) = value.get_mut("bundle").and_then(Value::as_table_mut) {
        for key in ["ruby", "optional_groups"] {
            if bundle
                .get(key)
                .and_then(Value::as_array)
                .is_some_and(Vec::is_empty)
            {
                bundle.remove(key);
            }
        }
    }
    if let Some(dependencies) = value.get_mut("dependencies").and_then(Value::as_table_mut) {
        dependencies.retain(|_, dependency| {
            let declarations = active_declarations(dependency.clone());
            let mut declarations = declarations.into_iter();
            let Some(mut primary) = declarations.next() else {
                return false;
            };
            let variants: Vec<_> = declarations.collect();
            if !variants.is_empty() {
                primary
                    .as_table_mut()
                    .unwrap()
                    .insert("variants".into(), Value::Array(variants));
            }
            *dependency = primary;
            true
        });
    }
    Ok(value)
}

pub(crate) fn render(value: &impl serde::Serialize) -> Result<String, toml::ser::Error> {
    crate::format::toml(render_normalized(value)?)
}

fn active_declarations(mut value: Value) -> Vec<Value> {
    let table = value.as_table_mut().unwrap();
    let variants = table
        .remove("variants")
        .and_then(|value| value.as_array().cloned())
        .unwrap_or_default();
    let enabled = table
        .remove("enabled")
        .and_then(|value| value.as_bool())
        .unwrap_or(true);
    if table
        .get("platforms")
        .and_then(Value::as_array)
        .is_some_and(Vec::is_empty)
    {
        table.remove("platforms");
    }
    let mut declarations = Vec::new();
    if enabled {
        declarations.push(value);
    }
    for variant in variants {
        declarations.extend(active_declarations(variant));
    }
    declarations
}

impl Manifest {
    /// Merges declarations with root project settings, rejecting explicit conflicts.
    pub fn merge_project(&self, project: &str) -> io::Result<String> {
        self.merge_project_format(project, crate::ExportFormat::Toml)
    }

    pub fn merge_project_format(
        &self,
        project: &str,
        format: crate::ExportFormat,
    ) -> io::Result<String> {
        let project = self.merged_project(project)?;
        match format {
            crate::ExportFormat::Toml => render(&project).map_err(invalid),
            crate::ExportFormat::Kdl => {
                crate::kdl::render(render_normalized(&project).map_err(invalid)?)
            }
        }
    }

    fn merged_project(&self, project: &str) -> io::Result<Table> {
        let project: Table = toml::from_str(project).map_err(invalid)?;
        let mut project = crate::sources::normalize_document(project).map_err(invalid)?;
        let mut dependencies = match project.remove("dependencies") {
            None => Table::new(),
            Some(Value::Table(value)) => value,
            Some(_) => return Err(invalid("dependencies must be a table")),
        };
        dependencies = crate::format::expand_dependencies(dependencies).map_err(invalid)?;
        for (name, value) in &mut dependencies {
            let parsed: Dependency = value.clone().try_into().map_err(invalid)?;
            parsed.validate().map_err(invalid)?;
            if let Some(gemfile) = self.dependencies.get(name) {
                let expected = Value::try_from(gemfile).map_err(invalid)?;
                let normalized = Value::try_from(&parsed).map_err(invalid)?;
                for key in value
                    .as_table()
                    .ok_or_else(|| invalid("dependency must be a string or table"))?
                    .keys()
                {
                    let key = if key == "ref" { "rev" } else { key };
                    if normalized.get(key) != expected.get(key) {
                        return Err(invalid(format!(
                            "Conflicting dependency {name}.{key} in Gemfile and rbproject.toml"
                        )));
                    }
                }
            }
            *value = Value::try_from(parsed).map_err(invalid)?;
        }
        for (name, dependency) in &self.dependencies {
            dependencies.insert(name.clone(), Value::try_from(dependency).map_err(invalid)?);
        }
        project.insert("dependencies".into(), Value::Table(dependencies));
        if !self.gemspecs.is_empty() {
            let generated = Value::try_from(&self.gemspecs).map_err(invalid)?;
            if project
                .get("gemspecs")
                .is_some_and(|value| value != &generated)
            {
                return Err(invalid(
                    "Conflicting gemspecs in Gemfile and rbproject.toml",
                ));
            }
            project.insert("gemspecs".into(), generated);
        }

        let mut bundle = match project.remove("bundle") {
            None => Table::new(),
            Some(Value::Table(value)) => value,
            Some(_) => return Err(invalid("bundle must be a table")),
        };
        let generated = Value::try_from(&self.bundle).map_err(invalid)?;
        let generated_table = generated.as_table().unwrap();
        let known: Table = bundle
            .iter()
            .filter(|(key, _)| generated_table.contains_key(*key))
            .map(|(key, value)| (key.clone(), value.clone()))
            .collect();
        let normalized =
            Value::try_from(Value::Table(known).try_into::<Bundle>().map_err(invalid)?)
                .map_err(invalid)?;
        for (key, value) in generated.as_table().unwrap() {
            if value.as_array().is_some_and(Vec::is_empty) {
                continue;
            }
            if bundle.contains_key(key) && normalized.get(key) != Some(value) {
                return Err(invalid(format!(
                    "Conflicting bundle.{key} in Gemfile and rbproject.toml"
                )));
            }
            bundle.insert(key.clone(), value.clone());
        }
        project.insert("bundle".into(), Value::Table(bundle));
        Ok(project)
    }
}

fn invalid(error: impl std::fmt::Display) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, error.to_string())
}
