use rb_gemfile::Evaluator;

fn manifest() -> rb_gemfile::Manifest {
    let root = tempfile::tempdir().unwrap();
    std::fs::write(
        root.path().join("Gemfile"),
        "source 'https://rubygems.org'\nruby '>= 3.2'\ngem 'rake', '>= 13', require: false\n",
    )
    .unwrap();
    Evaluator::new(std::env::var_os("RB_GEMFILE_RUBY").unwrap_or_else(|| "ruby".into()))
        .evaluate(root.path().join("Gemfile"))
        .unwrap()
        .manifest
}

#[test]
fn merges_root_settings_and_additional_dependencies() {
    let merged = manifest()
        .merge_project(include_str!(
            "fixtures/project/merges_root_settings_and_additional_dependencies-1.toml"
        ))
        .unwrap();
    assert!(merged.starts_with("# Generated by Ruby Butler. Do not edit.\n"));
    let value: toml::Value = toml::from_str(&merged).unwrap();
    assert_eq!(value["project"]["name"].as_str(), Some("sample"));
    assert_eq!(value["scripts"]["test"].as_str(), Some("rspec"));
    assert_eq!(value["bundle"]["without"][0].as_str(), Some("development"));
    let parsed = parsed_export(&merged);
    assert_eq!(
        parsed.dependencies["rake"].require,
        Some(rb_gemfile::Require::Enabled(false))
    );
    assert_eq!(parsed.dependencies["rack"].version, ["~> 3"]);
}

#[test]
fn rejects_explicit_dependency_and_bundle_conflicts() {
    for (project, message) in [
        ("[dependencies]\nrake = '< 12'", "rake.version"),
        ("[dependencies.rake]\nrequire = true", "rake.require"),
        ("[bundle]\nsource = 'https://other.test'", "bundle.source"),
        ("[bundle]\nruby = '< 3.0'", "bundle.ruby"),
        ("dependencies = 1", "dependencies must be a table"),
        (
            "[dependencies.rack]\ngit = 'url'\npath = '.'",
            "mutually exclusive",
        ),
        ("[dependencies.rack]\nunknown = true", "unknown field"),
    ] {
        let error = manifest().merge_project(project).unwrap_err().to_string();
        assert!(error.contains(message), "{project}: {error}");
    }
}

#[test]
fn accepts_empty_project_and_preserves_multiple_requirements() {
    let manifest = manifest();
    let merged = manifest.merge_project("").unwrap();
    assert_eq!(
        toml::from_str::<rb_gemfile::Manifest>(&merged).unwrap(),
        manifest
    );
    let merged = manifest
        .merge_project("[dependencies.rack]\nversion = ['>= 3', '< 4']\n")
        .unwrap();
    let parsed: rb_gemfile::Manifest = toml::from_str(&merged).unwrap();
    assert_eq!(parsed.dependencies["rack"].version, [">= 3", "< 4"]);
}

#[test]
fn exports_only_active_declarations_and_omits_redundant_fields() {
    let root = tempfile::tempdir().unwrap();
    std::fs::write(
        root.path().join("Gemfile"),
        include_str!(
            "fixtures/project/exports_only_active_declarations_and_omits_redundant_fields-1.rb"
        ),
    )
    .unwrap();
    let evaluation =
        Evaluator::new(std::env::var_os("RB_GEMFILE_RUBY").unwrap_or_else(|| "ruby".into()))
            .evaluate(root.path().join("Gemfile"))
            .unwrap();
    assert!(!evaluation.manifest.dependencies["excluded"].enabled);
    for output in [
        evaluation.manifest.to_toml().unwrap(),
        evaluation.manifest.merge_project("").unwrap(),
    ] {
        let value: toml::Value = toml::from_str(&output).unwrap();
        assert!(!output.contains("enabled ="));
        assert!(!output.contains("= []"));
        assert!(value["bundle"].get("ruby").is_none());
        let parsed = parsed_export(&output);
        assert!(!parsed.dependencies.contains_key("excluded"));
        assert_eq!(parsed.dependencies["mixed"].groups, ["development"]);
        assert_eq!(
            parsed.dependencies["mixed"].require,
            Some(rb_gemfile::Require::Name("mixed/runtime".into()))
        );
        assert!(parsed.dependencies["mixed"].variants.is_empty());
        assert_eq!(parsed.dependencies["active_first"].version, [">= 0"]);
        assert_eq!(
            parsed.dependencies["retained"].require,
            Some(rb_gemfile::Require::Enabled(false))
        );
        assert_eq!(
            parsed.dependencies["retained"].variants[0].platforms,
            ["jruby"]
        );
        let parsed: rb_gemfile::Manifest = toml::from_str(&output).unwrap();
        assert!(parsed.bundle.ruby.is_empty());
        assert!(parsed.bundle.optional_groups.is_empty());
        assert!(parsed.dependencies["mixed"].platforms.is_empty());
        assert!(parsed.dependencies["mixed"].enabled);
    }
}

#[test]
fn omits_disabled_root_dependencies() {
    let output = manifest()
        .merge_project("[dependencies.disabled]\nenabled = false\n")
        .unwrap();
    let parsed = parsed_export(&output);
    assert!(!parsed.dependencies.contains_key("disabled"));
    assert!(parsed.dependencies.contains_key("rake"));
}

fn parsed_export(input: &str) -> rb_gemfile::Manifest {
    let mut value: toml::Table = toml::from_str(input).unwrap();
    value.retain(|key, _| {
        matches!(
            key,
            "bundle" | "dependencies" | "sources" | "groups" | "gemspecs"
        )
    });
    if let Some(bundle) = value.get_mut("bundle").and_then(toml::Value::as_table_mut) {
        bundle.remove("without");
    }
    toml::Value::Table(value).try_into().unwrap()
}
