source 'https://rubygems.org'
gem 'rails', '~> 8.0'
group :development, :test do
  gem 'rake', '~> 13', require: false
end
group :production do
  gem 'rake', '~> 13', require: 'rake/task'
end
source 'https://gems.example.com' do
  gem 'internal', '~> 2.0'
end
source 'https://plugins.example.com' do
  gem 'plugin', platforms: :ruby
end
gem 'git-gem', git: 'https://github.com/example/gem', tag: 'v1.0'
