# Ruby Butler Configuration File
# 
# This configuration file allows you to set default values for Ruby Butler's
# global options. These defaults will be used when the corresponding CLI flags
# are not provided.
#
# Location:
#   Unix/Linux/macOS: ~/.config/rb/rb.toml (primary) or ~/.rb.toml (fallback)
#   Windows:          %APPDATA%\rb\rb.toml (primary) or ~\.rb.toml (fallback)
#
# Note: CLI arguments always take precedence over configuration file values.

# Designate the directory containing your Ruby installations
# Default: ~/.rubies
#
# This is where Ruby Butler will look for Ruby installations, typically
# directories named ruby-X.Y.Z (e.g., ruby-3.3.0, ruby-3.2.5)
#
# rubies-dir = "~/.rubies"
# rubies-dir = "/opt/rubies"

# Request a particular Ruby version for your environment
# Default: latest available version
#
# Specify which Ruby version to use by default. You can use:
# - Exact version: "3.3.0"
# - Major.minor: "3.3"
# - Just major: "3"
#
# ruby-version = "3.3"
# ruby-version = "3.3.0"

# Specify custom gem base directory
# Default: ~/.gem
#
# This is the base directory where gems will be installed. Ruby Butler
# will create version-specific subdirectories within this location
# (e.g., ~/.gem/ruby/3.3.0)
#
# gem-home = "~/.gem"
# gem-home = "/opt/gems"

# Example: Complete configuration
# Uncomment and adjust these values to suit your needs:
#
# rubies-dir = "~/.rubies"
# ruby-version = "3.3"
# gem-home = "~/.gem"
