use rb_core::butler::{ButlerError, ButlerRuntime};
use rb_gemfile::{Evaluator, ExportFormat, write_project};
use std::{
    ffi::OsStr,
    fs, io,
    io::Write,
    path::{Path, PathBuf},
};

pub fn find_gemfile(
    start: &Path,
    explicit: Option<&Path>,
    environment: Option<&OsStr>,
) -> io::Result<PathBuf> {
    if let Some(path) =
        explicit.or_else(|| environment.filter(|value| !value.is_empty()).map(Path::new))
    {
        let path = start.join(path);
        if !path.is_file() {
            return Err(io::Error::new(
                io::ErrorKind::NotFound,
                format!("Gemfile not found: {}", path.display()),
            ));
        }
        return fs::canonicalize(path);
    }
    for directory in start.ancestors() {
        for name in ["gems.rb", "Gemfile"] {
            let path = directory.join(name);
            if path.is_file() {
                return fs::canonicalize(path);
            }
        }
    }
    Err(io::Error::new(
        io::ErrorKind::NotFound,
        "No gems.rb or Gemfile found in the working directory or its parents",
    ))
}

pub fn export_gemfile_command(
    runtime: &ButlerRuntime,
    gemfile: &Path,
    project_file: Option<&Path>,
    output: Option<&Path>,
    format: ExportFormat,
) -> Result<(), ButlerError> {
    let ruby = runtime.selected_ruby()?.ruby_executable_path();
    export(runtime, &ruby, gemfile, project_file, output, format)
        .map_err(|error| ButlerError::General(error.to_string()))
}

fn export(
    runtime: &ButlerRuntime,
    ruby: &Path,
    gemfile: &Path,
    project_file: Option<&Path>,
    output: Option<&Path>,
    format: ExportFormat,
) -> io::Result<()> {
    let directory = gemfile.parent().unwrap();
    let default_project = directory.join("rbproject.toml");
    let project_path = project_file.unwrap_or(&default_project);
    if output.is_some_and(|output| fs::canonicalize(output).is_ok_and(|path| path == gemfile)) {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "The output must not overwrite the Gemfile",
        ));
    }
    let project = match fs::read_to_string(project_path) {
        Ok(project) if project.starts_with("# Generated by Ruby Butler. Do not edit.\n") => {
            let mut settings: toml::Table = toml::from_str(&project).map_err(io::Error::other)?;
            for key in ["dependencies", "sources", "groups", "bundle", "gemspecs"] {
                settings.remove(key);
            }
            toml::to_string(&settings).map_err(io::Error::other)?
        }
        Ok(project) => project,
        Err(error) if error.kind() == io::ErrorKind::NotFound && project_file.is_none() => {
            let name = directory
                .file_name()
                .unwrap_or(OsStr::new("project"))
                .to_string_lossy();
            let project = toml::Table::from_iter([(
                "project".into(),
                toml::Value::Table(toml::Table::from_iter([(
                    "name".into(),
                    toml::Value::String(name.into_owned()),
                )])),
            )]);
            toml::to_string(&project).map_err(io::Error::other)?
        }
        Err(error) => return Err(error),
    };
    let mut evaluator = Evaluator::new(ruby);
    for (key, value) in runtime.env_vars(std::env::var("PATH").ok()) {
        evaluator = evaluator.env(key, value);
    }
    let evaluation = evaluator.env("BUNDLE_GEMFILE", gemfile).evaluate(gemfile)?;
    eprint!("{}{}", evaluation.stdout, evaluation.stderr);
    let mut project = evaluation.manifest.merge_project_format(&project, format)?;
    let prefix = match format {
        ExportFormat::Toml => "#",
        ExportFormat::Kdl => "//",
    };
    let mut sources = format!("{prefix} Source Gemfile: {gemfile:?}\n");
    if project_path.is_file() {
        sources.push_str(&format!("{prefix} Project settings: {project_path:?}\n"));
    }
    let guidance = format!("{prefix} Edit the source Gemfile and project settings instead.\n");
    project = project.replacen(&guidance, &sources, 1);
    if let Some(output) = output {
        write_project(output, &project)?;
        eprintln!("Exported {} to {}", gemfile.display(), output.display());
    } else {
        io::stdout().lock().write_all(project.as_bytes())?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn discovers_nearest_gemfile_and_prefers_gems_rb() {
        let root = tempfile::tempdir().unwrap();
        let child = root.path().join("nested");
        fs::create_dir(&child).unwrap();
        fs::write(root.path().join("gems.rb"), "").unwrap();
        fs::write(child.join("Gemfile"), "").unwrap();
        assert_eq!(
            find_gemfile(&child, None, None).unwrap(),
            fs::canonicalize(child.join("Gemfile")).unwrap()
        );
        fs::write(child.join("gems.rb"), "").unwrap();
        assert_eq!(
            find_gemfile(&child, None, None).unwrap(),
            fs::canonicalize(child.join("gems.rb")).unwrap()
        );
        fs::remove_file(child.join("gems.rb")).unwrap();
        fs::remove_file(child.join("Gemfile")).unwrap();
        assert_eq!(
            find_gemfile(&child, None, Some(OsStr::new(""))).unwrap(),
            fs::canonicalize(root.path().join("gems.rb")).unwrap()
        );
    }

    #[test]
    fn explicit_file_overrides_environment_and_missing_overrides_do_not_fall_back() {
        let root = tempfile::tempdir().unwrap();
        fs::write(root.path().join("Gemfile"), "").unwrap();
        fs::write(root.path().join("custom.rb"), "").unwrap();
        assert_eq!(
            find_gemfile(root.path(), None, Some(OsStr::new("custom.rb"))).unwrap(),
            fs::canonicalize(root.path().join("custom.rb")).unwrap()
        );
        assert_eq!(
            find_gemfile(
                root.path(),
                Some(Path::new("Gemfile")),
                Some(OsStr::new("missing"))
            )
            .unwrap(),
            fs::canonicalize(root.path().join("Gemfile")).unwrap()
        );
        for (explicit, environment) in [
            (Some(Path::new("missing")), None),
            (None, Some(OsStr::new("missing"))),
        ] {
            assert_eq!(
                find_gemfile(root.path(), explicit, environment)
                    .unwrap_err()
                    .kind(),
                io::ErrorKind::NotFound
            );
        }
    }
}
