#![cfg(unix)]

use std::{
    fs,
    os::unix::fs::PermissionsExt,
    path::Path,
    process::{Command, Output},
};

struct Fixture {
    root: tempfile::TempDir,
}

impl Fixture {
    fn new() -> Self {
        let root = tempfile::tempdir().unwrap();
        let bin = root.path().join("rubies/ruby-9.9.9/bin");
        fs::create_dir_all(&bin).unwrap();
        let ruby =
            which::which(std::env::var_os("RB_GEMFILE_RUBY").unwrap_or_else(|| "ruby".into()))
                .unwrap();
        let quoted = ruby.to_str().unwrap().replace('\'', "'\\''");
        fs::write(
            bin.join("ruby"),
            format!("#!/bin/sh\nexec '{quoted}' \"$@\"\n"),
        )
        .unwrap();
        fs::set_permissions(bin.join("ruby"), fs::Permissions::from_mode(0o755)).unwrap();
        fs::write(root.path().join("config.toml"), "").unwrap();
        fs::create_dir(root.path().join("tea-room")).unwrap();
        Self { root }
    }

    fn project(&self) -> std::path::PathBuf {
        self.root.path().join("tea-room")
    }

    fn command(&self) -> Command {
        let mut command = Command::new(env!("CARGO_BIN_EXE_rb"));
        command
            .current_dir(self.root.path())
            .args(["-c", "config.toml", "-r", "9.9.9"])
            .env("RB_RUBIES_DIR", self.root.path().join("rubies"))
            .env_remove("BUNDLE_GEMFILE")
            .env_remove("RB_PROJECT")
            .env_remove("RB_WORK_DIR")
            .env_remove("RB_NO_BUNDLER")
            .env_remove("RB_LOG_LEVEL")
            .env_remove("RB_VERBOSE")
            .env_remove("RB_VERY_VERBOSE");
        command
    }

    fn run(&self, args: &[&str]) -> Output {
        self.command().args(args).output().unwrap()
    }
}

fn success(output: &Output) {
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
}

fn stdout(output: &Output) -> toml::Value {
    normalize_export(toml::from_str(std::str::from_utf8(&output.stdout).unwrap()).unwrap())
}

fn read(path: impl AsRef<Path>) -> toml::Value {
    normalize_export(toml::from_str(&fs::read_to_string(path).unwrap()).unwrap())
}

fn normalize_export(mut value: toml::Value) -> toml::Value {
    let mut model = value.as_table().unwrap().clone();
    model.retain(|key, _| {
        matches!(
            key,
            "bundle" | "dependencies" | "sources" | "groups" | "gemspecs"
        )
    });
    let manifest: rb_gemfile::Manifest = toml::Value::Table(model).try_into().unwrap();
    let mut dependencies = toml::Table::new();
    for (name, dependency) in &manifest.dependencies {
        let default = rb_gemfile::Dependency {
            version: dependency.version.clone(),
            ..Default::default()
        };
        let entry = if dependency == &default && dependency.version.len() == 1 {
            toml::Value::String(dependency.version[0].clone())
        } else {
            toml::Value::try_from(dependency).unwrap()
        };
        dependencies.insert(name.clone(), entry);
    }
    for (_, dependency) in &mut dependencies {
        if let Some(table) = dependency.as_table_mut() {
            table.remove("enabled");
        }
    }
    value
        .as_table_mut()
        .unwrap()
        .insert("dependencies".into(), toml::Value::Table(dependencies));
    let bundle = value
        .as_table_mut()
        .unwrap()
        .entry("bundle")
        .or_insert_with(|| toml::Value::Table(toml::Table::new()));
    if let Some(source) = manifest.bundle.source {
        bundle
            .as_table_mut()
            .unwrap()
            .insert("source".into(), toml::Value::String(source));
    }
    value
}

#[test]
fn exports_with_work_dir_and_initializes_missing_project_settings() {
    let fixture = Fixture::new();
    fs::write(
        fixture.project().join("Gemfile"),
        "raise 'Bundler was loaded' if Gem.loaded_specs.key?('bundler'); source 'https://rubygems.org'; gem 'rake', require: false",
    )
    .unwrap();
    let output = fixture.run(&["export-gemfile", "-C", "tea-room", "-R", "../rubies"]);
    success(&output);
    let project = stdout(&output);
    assert_eq!(project["project"]["name"].as_str(), Some("tea-room"));
    assert_eq!(
        project["dependencies"]["rake"]["require"].as_bool(),
        Some(false)
    );
    assert!(
        !std::str::from_utf8(&output.stdout)
            .unwrap()
            .contains("enabled")
    );
    let raw: toml::Value = toml::from_str(std::str::from_utf8(&output.stdout).unwrap()).unwrap();
    assert!(raw.get("sources").is_some());
    assert!(
        String::from_utf8_lossy(&output.stdout)
            .starts_with("# Generated by Ruby Butler. Do not edit.\n")
    );
    assert!(!fixture.project().join("rbproject.toml").exists());
    assert!(!fixture.project().join("Gemfile.lock").exists());
}

#[test]
fn selects_gems_rb_and_searches_parents() {
    let fixture = Fixture::new();
    fs::write(fixture.project().join("Gemfile"), "raise 'wrong file'").unwrap();
    fs::write(fixture.project().join("gems.rb"), "gem 'rake'").unwrap();
    fs::create_dir(fixture.project().join("nested")).unwrap();
    let output = fixture.run(&[
        "-C",
        "tea-room/nested",
        "-R",
        "../../rubies",
        "export-gemfile",
    ]);
    success(&output);
    assert!(stdout(&output)["dependencies"].get("rake").is_some());
    assert!(!fixture.project().join("rbproject.toml").exists());
    assert!(!fixture.project().join("nested/rbproject.toml").exists());
}

#[test]
fn argument_overrides_environment_and_empty_environment_uses_discovery() {
    let fixture = Fixture::new();
    fs::write(fixture.project().join("Gemfile"), "gem 'rake'").unwrap();
    fs::write(fixture.project().join("custom.rb"), "raise 'wrong file'").unwrap();
    let output = fixture
        .command()
        .env("BUNDLE_GEMFILE", "tea-room/custom.rb")
        .args(["export-gemfile", "tea-room/Gemfile"])
        .output()
        .unwrap();
    success(&output);
    let output = fixture
        .command()
        .env("BUNDLE_GEMFILE", "")
        .args(["-C", "tea-room", "-R", "../rubies", "export-gemfile"])
        .output()
        .unwrap();
    success(&output);
}

#[test]
fn environment_paths_are_relative_to_work_dir_and_evaluation_receives_selected_file() {
    let fixture = Fixture::new();
    fs::write(fixture.project().join("custom.rb"), "raise 'wrong BUNDLE_GEMFILE' unless File.expand_path(ENV.fetch('BUNDLE_GEMFILE')) == __FILE__; gem 'rack'").unwrap();
    let output = fixture
        .command()
        .env("BUNDLE_GEMFILE", "custom.rb")
        .args([
            "-C",
            "tea-room",
            "-R",
            "../rubies",
            "export-gemfile",
            "--output",
            "export/result.toml",
        ])
        .output()
        .unwrap();
    success(&output);
    assert!(
        read(fixture.project().join("export/result.toml"))["dependencies"]
            .get("rack")
            .is_some()
    );
}

#[test]
fn global_project_input_preserves_settings_and_rejects_conflicts_without_writing() {
    let fixture = Fixture::new();
    fs::write(fixture.project().join("Gemfile"), "gem 'rake', '>= 13'").unwrap();
    let destination = fixture.root.path().join("custom.toml");
    fs::write(
        &destination,
        include_str!("fixtures/export_gemfile_tests/global_project_input_preserves_settings_and_rejects_conflicts_without_writing-1.toml"),
    )
    .unwrap();
    let before = fs::read_to_string(&destination).unwrap();
    let output = fixture.run(&["-P", "custom.toml", "export-gemfile", "tea-room/Gemfile"]);
    success(&output);
    let parsed = stdout(&output);
    assert_eq!(fs::read_to_string(&destination).unwrap(), before);
    assert_eq!(parsed["project"]["name"].as_str(), Some("kept"));
    assert_eq!(parsed["scripts"]["test"].as_str(), Some("rspec"));
    let original = "[dependencies]\nrake='< 12'\n";
    fs::write(&destination, original).unwrap();
    let output = fixture.run(&["export-gemfile", "tea-room/Gemfile", "-P", "custom.toml"]);
    assert!(!output.status.success());
    assert!(
        String::from_utf8_lossy(&output.stderr).contains("Conflicting dependency rake.version")
    );
    assert_eq!(fs::read_to_string(&destination).unwrap(), original);
}

#[test]
fn failures_do_not_overwrite_destination_or_input() {
    let fixture = Fixture::new();
    let gemfile = fixture.project().join("Gemfile");
    fs::write(&gemfile, "gem 'rake'").unwrap();
    let output = fixture.run(&[
        "export-gemfile",
        "tea-room/Gemfile",
        "-o",
        "tea-room/Gemfile",
    ]);
    assert!(!output.status.success());
    assert_eq!(fs::read_to_string(&gemfile).unwrap(), "gem 'rake'");
    let project = fixture.project().join("rbproject.toml");
    fs::write(&project, "[project]\nname='kept'").unwrap();
    fs::write(&gemfile, "raise 'deliberate failure'").unwrap();
    let output = fixture.run(&["export-gemfile", "tea-room/Gemfile"]);
    assert!(!output.status.success());
    assert!(String::from_utf8_lossy(&output.stderr).contains("deliberate failure"));
    assert_eq!(
        fs::read_to_string(project).unwrap(),
        "[project]\nname='kept'"
    );
    let output = fixture
        .command()
        .env("BUNDLE_GEMFILE", "missing")
        .arg("export-gemfile")
        .output()
        .unwrap();
    assert!(!output.status.success());
    assert!(String::from_utf8_lossy(&output.stderr).contains("Gemfile not found"));
}

#[test]
fn utility_is_listed_in_help() {
    let fixture = Fixture::new();
    let output = fixture.run(&["help"]);
    success(&output);
    assert!(String::from_utf8_lossy(&output.stdout).contains("export-gemfile"));
    let output = fixture.run(&["help", "export-gemfile"]);
    success(&output);
    let help = String::from_utf8_lossy(&output.stdout);
    assert!(help.contains("BUNDLE_GEMFILE"));
    assert!(help.contains("--output"));
    assert!(help.contains("[GEMFILE]"));
}

#[test]
fn reexport_replaces_generated_declarations_and_preserves_project_settings() {
    let fixture = Fixture::new();
    let gemfile = fixture.project().join("Gemfile");
    fs::write(
        &gemfile,
        "source 'https://rubygems.org'; gem 'rake', '>= 13'; gem 'removed'",
    )
    .unwrap();
    let project = fixture.project().join("rbproject.toml");
    fs::write(
        &project,
        include_str!("fixtures/export_gemfile_tests/reexport_replaces_generated_declarations_and_preserves_project_settings-1.toml"),
    )
    .unwrap();
    success(&fixture.run(&[
        "export-gemfile",
        "tea-room/Gemfile",
        "-o",
        "tea-room/rbproject.toml",
    ]));
    fs::write(&gemfile, "source 'https://other.test'; gem 'rake', '>= 14'; install_if -> { ENV['WITH_DEBUG'] == '1' } do\n gem 'debug'\nend").unwrap();
    for enabled in ["1", "0"] {
        let output = fixture
            .command()
            .env("WITH_DEBUG", enabled)
            .args([
                "export-gemfile",
                "tea-room/Gemfile",
                "-o",
                "tea-room/rbproject.toml",
            ])
            .output()
            .unwrap();
        success(&output);
        assert!(output.stdout.is_empty());
        let parsed = read(&project);
        assert_eq!(parsed["project"]["name"].as_str(), Some("kept"));
        assert_eq!(parsed["scripts"]["test"].as_str(), Some("rspec"));
        assert_eq!(
            parsed["bundle"]["source"].as_str(),
            Some("https://other.test")
        );
        assert_eq!(parsed["dependencies"]["rake"].as_str(), Some(">= 14"));
        assert!(parsed["dependencies"].get("removed").is_none());
        assert_eq!(
            parsed["dependencies"].get("debug").is_some(),
            enabled == "1"
        );
    }
}

#[test]
fn global_project_input_and_output_are_independent() {
    let fixture = Fixture::new();
    fs::write(fixture.project().join("Gemfile"), "gem 'rake'").unwrap();
    let input = fixture.project().join("from-env.toml");
    let original = "[project]\nname='from environment'\n";
    fs::write(&input, original).unwrap();
    let output = fixture
        .command()
        .env("RB_WORK_DIR", "tea-room")
        .env("RB_PROJECT", "from-env.toml")
        .args(["export-gemfile", "--output", "chosen.toml"])
        .output()
        .unwrap();
    success(&output);
    assert!(output.stdout.is_empty());
    assert!(String::from_utf8_lossy(&output.stderr).contains("Exported"));
    assert_eq!(
        read(fixture.project().join("chosen.toml"))["project"]["name"].as_str(),
        Some("from environment")
    );
    assert_eq!(fs::read_to_string(&input).unwrap(), original);
    assert!(!fixture.project().join("rbproject.toml").exists());
    let output = fixture
        .command()
        .env("RB_WORK_DIR", "tea-room")
        .env("RB_PROJECT", "from-env.toml")
        .arg("export-gemfile")
        .output()
        .unwrap();
    success(&output);
    assert_eq!(
        stdout(&output)["project"]["name"].as_str(),
        Some("from environment")
    );
    assert_eq!(fs::read_to_string(input).unwrap(), original);
}

#[test]
fn global_project_flag_overrides_environment_before_and_after_command() {
    let fixture = Fixture::new();
    fs::write(fixture.project().join("Gemfile"), "gem 'rake'").unwrap();
    fs::write(
        fixture.project().join("settings.toml"),
        "[project]\nname='CLI settings'\n",
    )
    .unwrap();
    for args in [
        vec!["-C", "tea-room", "-P", "settings.toml", "export-gemfile"],
        vec!["export-gemfile", "-C", "tea-room", "-P", "settings.toml"],
    ] {
        let output = fixture
            .command()
            .env("RB_PROJECT", "missing-env.toml")
            .args(args)
            .output()
            .unwrap();
        success(&output);
        assert_eq!(
            stdout(&output)["project"]["name"].as_str(),
            Some("CLI settings")
        );
        assert!(!fixture.project().join("rbproject.toml").exists());
    }
}

#[test]
fn diagnostics_do_not_contaminate_stdout_and_missing_project_override_is_an_error() {
    let fixture = Fixture::new();
    fs::write(
        fixture.project().join("Gemfile"),
        "puts 'Gemfile message'; warn 'Gemfile warning'; gem 'rake'",
    )
    .unwrap();
    let output = fixture.run(&["-v", "export-gemfile", "tea-room/Gemfile"]);
    success(&output);
    assert!(stdout(&output)["dependencies"].get("rake").is_some());
    let diagnostics = String::from_utf8_lossy(&output.stderr);
    assert!(diagnostics.contains("Gemfile message"));
    assert!(diagnostics.contains("Gemfile warning"));
    assert!(!String::from_utf8_lossy(&output.stdout).contains("Gemfile message"));
    let destination = fixture.root.path().join("result.toml");
    fs::write(&destination, "existing output").unwrap();
    let output = fixture.run(&[
        "export-gemfile",
        "tea-room/Gemfile",
        "-P",
        "missing.toml",
        "-o",
        "result.toml",
    ]);
    assert!(!output.status.success());
    assert!(output.stdout.is_empty());
    assert_eq!(fs::read_to_string(destination).unwrap(), "existing output");
}

#[test]
fn optional_kdl_output_uses_the_same_global_project_settings() {
    let fixture = Fixture::new();
    fs::write(fixture.project().join("Gemfile"), "gem 'rails', '~> 8.0'; source 'https://gems.example.com' do\n gem 'internal', '~> 2.0', require: false\nend").unwrap();
    fs::write(
        fixture.project().join("settings.toml"),
        "[project]\nname='shared settings'\n",
    )
    .unwrap();
    for output_file in [None, Some("result.kdl")] {
        let mut command = fixture.command();
        command
            .env("RB_WORK_DIR", "tea-room")
            .env("RB_PROJECT", "settings.toml")
            .args(["export-gemfile", "--format", "kdl"]);
        if let Some(path) = output_file {
            command.args(["--output", path]);
        }
        let output = command.output().unwrap();
        success(&output);
        let text = if let Some(path) = output_file {
            assert!(output.stdout.is_empty());
            fs::read_to_string(fixture.project().join(path)).unwrap()
        } else {
            String::from_utf8(output.stdout).unwrap()
        };
        let document: kdl::KdlDocument = text.parse().unwrap();
        assert_eq!(
            document
                .get("project")
                .unwrap()
                .children()
                .unwrap()
                .get("name")
                .unwrap()
                .get(0)
                .unwrap()
                .as_string(),
            Some("shared settings")
        );
        let source = document
            .nodes()
            .iter()
            .find(|node| node.name().value() == "source")
            .unwrap();
        assert_eq!(
            source.get(0).unwrap().as_string(),
            Some("https://gems.example.com")
        );
        let gem = source
            .children()
            .unwrap()
            .nodes()
            .iter()
            .find(|node| node.get(0).and_then(kdl::KdlValue::as_string) == Some("internal"))
            .unwrap();
        assert_eq!(gem.get("require").unwrap().as_bool(), Some(false));
    }
    assert!(!fixture.project().join("rbproject.toml").exists());
    let output = fixture.run(&["export-gemfile", "--format", "yaml"]);
    assert!(!output.status.success());
    assert!(output.stdout.is_empty());
}

#[test]
fn toml_source_blocks_from_global_settings_merge_into_export() {
    let fixture = Fixture::new();
    fs::write(fixture.project().join("Gemfile"), "gem 'rails', '~> 8.0'").unwrap();
    fs::write(
        fixture.project().join("settings.toml"),
        "[[sources]]\nurl='https://gems.example.com'\n[sources.dependencies]\ninternal='~> 2.0'\n",
    )
    .unwrap();
    let output = fixture.run(&[
        "export-gemfile",
        "tea-room/Gemfile",
        "-P",
        "tea-room/settings.toml",
    ]);
    success(&output);
    let parsed = stdout(&output);
    assert_eq!(parsed["dependencies"]["rails"].as_str(), Some("~> 8.0"));
    assert_eq!(
        parsed["dependencies"]["internal"]["version"].as_str(),
        Some("~> 2.0")
    );
}

#[test]
fn legacy_generated_header_refreshes_dependencies_and_identifies_sources() {
    let fixture = Fixture::new();
    fs::write(fixture.project().join("Gemfile"), "gem 'rake'").unwrap();
    fs::write(
        fixture.project().join("rbproject.toml"),
        include_str!("fixtures/export_gemfile_tests/legacy_generated.toml"),
    )
    .unwrap();
    let output = fixture.run(&["-C", "tea-room", "export-gemfile"]);
    success(&output);
    let parsed = stdout(&output);
    assert_eq!(parsed["project"]["name"].as_str(), Some("kept"));
    assert!(parsed["dependencies"].get("removed").is_none());
    assert!(parsed["dependencies"].get("rake").is_some());
    let text = String::from_utf8(output.stdout).unwrap();
    assert!(text.contains("# Source Gemfile:"));
    assert!(text.contains("# Project settings:"));
    assert!(text.contains("Regenerate with rb export-gemfile"));
}
